name: biuld test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest #前ページのコンテナを使うという宣言
    steps:
      - uses: actions/checkout@v2    #コンテナのカレントディレクトリにリポジトリを配置
          
      - name: build
        run: |
          rsync -av ./ /root/ros2_ws/src/joint_msgs/    # リポジトリの下をros2_ws下にコピー
          cd /root/ros2_ws
          sudo apt-get update
          sudo apt-get -y install ament-cmake
          colcon build
